run:
  concurrency: 2
  timeout: 5m
  go: 1.20

linter-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
